export const SIMPLES_KEYWORDS = [
  'programa',
  'inicio',
  'fim',
  'inteiro',
  'flutuante',
  'vazio',
  'se',
  'entao',
  'senao',
  'fimse',
  'enquanto',
  'fimenquanto',
  'para',
  'de',
  'ate',
  'passo',
  'faca',
  'fimpara',
  'leia',
  'escreva',
  'escreval',
  'e',
  'ou',
  'nao',
  'div',
  'procedimento',
  'retorna',
] as const

export const SIMPLES_OPERATORS = ['<-', '+', '-', '*', 'div', '>', '<', '=', '<>', '>=', '<=']
